[package]
name = "billyjoule"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.4.0"
log = "0.4.17"
serenity = "0.11.5"
tokio = { version = "1.27.0", features = ["tracing", "macros", "rt-multi-thread"] }
opentelemetry = "0.19.0"
tracing-subscriber = "0.3.16"
tracing-opentelemetry = "0.18.0"
opentelemetry-jaeger = "0.18.0"
opentelemetry_sdk = "0.19.0"
