services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      - /opt/billyjoule/billyjoule
      - --max-message-age=20h
    env_file:
      billyjoule.env
    ports:
      - 59091:9090
  meili:
    image: docker.io/getmeili/meilisearch:v1.2
    ports:
      - 7700:7700
