version: "2"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      - /opt/billyjoule/billyjoule
      - --max-message-age=20h
    env_file:
      billyjoule.env
    ports:
      - 59090:9090

