apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: billyjoule

images:
- name: IMAGENAME:TAG
  newName: docker.io/petergrace/billyjoule
  newTag: v0.9.4

resources:
- ns.yaml
- sa.yaml
- deployment.yaml
- secret.yaml
- svc-meili.yaml
- ss-meili.yaml
- meili-secret.yaml
