apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: billyjoule

images:
- name: IMAGENAME:TAG
  newName: docker.io/petergrace/billyjoule
  newTag: v0.5.0

resources:
- ns.yaml
- sa.yaml
- deployment.yaml
- secret.yaml
