apiVersion: v1
kind: Secret
metadata:
  name: billyjoule-env
  namespace: billyjoule
  annotations:
    vault.security.banzaicloud.io/vault-addr: https://keimvault.vault:8200
    vault.security.banzaicloud.io/vault-role: billyjoule
    vault.security.banzaicloud.io/vault-skip-verify: "true"
stringData:
  DISCORD_TOKEN: vault:kv/data/billyjoule#DISCORD_TOKEN
  GUILD_ID: vault:kv/data/billyjoule#GUILD_ID
  CHANNEL_ID: vault:kv/data/billyjoule#CHANNEL_ID
  LOG_CHANNEL_ID: vault:kv/data/billyjoule#LOG_CHANNEL_ID
  AWS_ACCESS_KEY_ID: vault:kv/data/billyjoule#AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: vault:kv/data/billyjoule#AWS_SECRET_ACCESS_KEY
  EMOJI_S3_ENDPOINT: vault:kv/data/billyjoule#EMOJI_S3_ENDPOINT
  EMOJI_S3_BUCKET: vault:kv/data/billyjoule#EMOJI_S3_BUCKET
  MEILISEARCH_URL: vault:kv/data/billyjoule#MEILISEARCH_URL
  MEILISEARCH_KEY: vault:kv/data/billyjoule#MEILISEARCH_KEY
