apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: meilisearch
  name: meilisearch-headless
  namespace: billyjoule
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app.kubernetes.io/name: meilisearch
  sessionAffinity: None
  type: ClusterIP
