name: Check-n-Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    
jobs:
  generate: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
